services:
  core-operational-backend:
    build: .
    container_name: core-operational-backend
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 172.31.253.50:9092
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - cache-network

networks:
  cache-network:
    external: true
