services:
  mocks:
    build: .
    container_name: mocks
    environment:
      - MQTT_BROKER_HOST=mqtt
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=sensor/data
    networks:
      - cache-network

networks:
  cache-network:
    external: true
